import { Nft } from './types'

const Nfts: Nft[] = [
  {
    name: 'Count Pepes Chocula',
    metadata: 'tier-NFT-base-dark-chocolate.json',
    description: 'Dipped in chocolate and ready for a bite. Part of the base tier of Vlad NFTs.',
    previewImage: 'preview-base-dark-chocolate.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmX9UuF41nfhnESX3DnVHhC4XwuYAcLEReGyN4CtE8P7Bg?filename=NFT-base-dark-chocolate.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 0,
    nftId: 0,
    tokenAmount: 10,
    tokenSupply: 2222,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Vlad Pepes Drakul',
    metadata: 'tier-NFT-base-main-nopaint.json',
    description: 'The legend behind the meme in all his original glory. Part of the base tier of Vlad NFTs',
    previewImage: 'preview-base-main-nopaint.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmWckPrzbjvf8jqUpdQ7jKLzdaSBTyPSV6x6obSUHHipqc?filename=NFT-base-main-nopaint.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 1,
    nftId: 1,
    tokenAmount: 10,
    tokenSupply: 2222,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Pepes in Stone',
    metadata: 'tier-NFT-base-marble.json',
    description:
      'The count has turned into a marble statue ready for display in the halls of Vladhalla. Part of the base tier of Vlad NFTs.',
    previewImage: 'preview-base-marble.jpg',
    originalImage: 'https://ipfs.io/ipfs/QmSnz85drLjCD4qNgaMwHFC6PFEkGrmYhM1LpHwZWpEWaQ?filename=NFT-base-marble.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 2,
    nftId: 2,
    tokenAmount: 10,
    tokenSupply: 2222,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'The path to Vladhalla',
    metadata: '',
    description: 'All who seek to find the path to Vladhalla must have strong hands along the way to immortality.',
    previewImage: 'preview-path-to-vladhalla.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmQWAeV3aAWD2Kbvxmtt4H874AEf7M7N5FcBos4iZbkRcj?filename=NFT-rare-path-to-vladhalla.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 3,
    nftId: 3,
    tokenAmount: 100,
    tokenSupply: 666,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Painted Pepe',
    metadata: '',
    description:
      'As an homage to the original Vlad Pepes Drakul this retains his painted face hang him in your gallery for eternal viewing.',
    previewImage: 'preview-painted-pepes.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmRqe92vpppkNS2aihmdvswHstAiHAF4jC2KUAiec5LKKk?filename=NFT-rare-painted-pepes.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 4,
    nftId: 4,
    tokenAmount: 100,
    tokenSupply: 666,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'All Hail VLAD',
    metadata: '',
    description: 'A coin like no other. It grants the holder eternal life when stored in thier wallet.',
    previewImage: 'preview-all-hail-vlad.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmWmdegkuvXShBs47G4GPqxfwnVbtKY5pYeAoAN3Xy37KV?filename=NFT-rare-all-hail-vlad.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 5,
    nftId: 5,
    tokenAmount: 100,
    tokenSupply: 666,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Silver Pepes',
    metadata: '',
    description:
      "The count has had an epic existence sure, but it has not been without many attempts at his alife. This artist's rendition pays homage to the time he was frozen in Carbonite ...oh wait, wrong story. Our bad, pretty slick tho right?",
    previewImage: 'preview-silver-pepe.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmaPP3CqB8iNcB9b9NCZVytNiaxZcJWt7Kk1vnHWwRL7hQ?filename=NFT-epic-silver-pepes.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 0,
    nftId: 0,
    tokenAmount: 350,
    tokenSupply: 66,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Bank of Vladhalla',
    metadata: '',
    description:
      "They say when you leave this alife you can't take it with you... Well, who's leaving? That's for mortals to worry about.",
    previewImage: 'preview-bank-of-vlad.png',
    originalImage:
      'https://ipfs.io/ipfs/Qma87NMJAu33nQuCRvoAK4MwP9CBwhGsLkQdTptM6uxoyp?filename=NFT-epic-bank-of-vladhalla.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 1,
    nftId: 1,
    tokenAmount: 350,
    tokenSupply: 66,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Gates of Vladhalla',
    metadata: '',
    description:
      'Tales have been written of the select few who have made it this far. The  sheer majesty of these very gates would make the hairs on their arms stand on end. Only the immortal shall pass through - will you?',
    previewImage: 'preview-gate-of-vlad.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmW1az8XriRqdx2zXY7w71XFxXUEfH5hUsyZTzwGBe7gfh?filename=NFT-epic-gates-of-vladhalla.png',
    fileType: 'png',
    blurImage: '',
    sortOrder: 2,
    nftId: 2,
    tokenAmount: 350,
    tokenSupply: 66,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Golden Pepes',
    metadata: '',
    description:
      'For a brief period in time Pepe Drakul led a very powerful unit known as the 7 golden Vampires. He commissioned a bust made of the purest gold to commemorate his time with them.',
    previewImage: 'preview-golden-pepes.jpg',
    originalImage:
      'https://ipfs.io/ipfs/Qmdv1t4kUa8YSP8rpZTXLKvpycnijWJdCSpjsN8sjArGx8?filename=NFT-legendary-pepes-gold.mp4',
    fileType: 'mp4',
    blurImage: '',
    sortOrder: 3,
    nftId: 3,
    tokenAmount: 1200,
    tokenSupply: 6,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'Immortality',
    metadata: '',
    description:
      'Those who have ever held the Chalice of ALIFE are granted Immortality. Do not fear eternal sleep/slumber, for it will not come for you.',
    previewImage: 'preview-immortality.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmaHeTsV6AnhqWDAeBUvwmQbo7RC6bM1jQzVQUCQSLg9Bp?filename=NFT-legendary-immortality.png',
    fileType: 'png',
    blurImage: '',
    sortOrder: 4,
    nftId: 4,
    tokenAmount: 1200,
    tokenSupply: 6,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
  {
    name: 'The VladFather',
    metadata: '',
    description:
      'His sceptre slammed into the marble floor with a crack, prompting the artist to begin. How many final breaths has that hand taken from his enemies? His eyes, wildly electric and filled with menace, and a stance that dares you to make your move. I don’t envy the one tasked with creating this portrait. Pepe Drakul has only ever posed for one drawing and this is it.',
    previewImage: 'preview-the-vladfather.jpg',
    originalImage:
      'https://ipfs.io/ipfs/QmVEdevPc1nFLJrFQK4GsJtcS5486uaQE73mo7aKjw13ph?filename=NFT-legendary-vlad-father.png',
    fileType: 'png',
    blurImage: '',
    sortOrder: 5,
    nftId: 5,
    tokenAmount: 1200,
    tokenSupply: 6,
    nftFarmContract: '0x3627Ca89675b42489aD39619A92dd0Ce24CA90bB',
    nftContract: '0xa521D5FA64D0aAdB4ee607BAb20142aA173e4392',
    bunnyId: 0,
  },
]

export default Nfts
